import React from 'react';
import { geographyLinks, relatedGeography } from '../../data/geographyPages';
import { spaceCollections } from '../../data/spacePages';
import shared from '../SpacePage/SpacePage.module.css';
import styles from './GeographyPage.module.css';

const Arrow = () => <span aria-hidden="true">↗</span>;
const themes = { district: ['#eef1e8', '#536047'], city: ['#f1f6fa', '#346b8d'], landscape: ['#f4eee5', '#805e35'] };
const stages = [
  ['Участок и задача', 'По плану и фотографиям обсуждаем возрастные группы, ограничения и желаемые сценарии. Фиксируем, какие исходные данные ещё нужны.'],
  ['Концепция и комплектация', 'Подбираем оборудование, уточняем расстановку, материалы и связанные работы. Состав предложения согласуем с командой проекта.'],
  ['Поставка и реализация', 'Проверяем готовность основания, доступ для разгрузки и формат монтажных работ. Сроки и стоимость рассчитываем для согласованного состава и адреса.'],
];

export default function GeographyPage({ page }) {
  const [wash, accent] = themes[page.layout];
  const related = relatedGeography(page);
  const visual = spaceCollections[page.collections[0]];
  const district = page.layout === 'district';
  const mail = `mailto:info@ludno.ru?subject=${encodeURIComponent(page.title)}&body=${encodeURIComponent('Здравствуйте! Планируем площадку ' + page.where + '.\n\nАдрес объекта: \nТип территории: \nВозраст пользователей: \nЖелаемые сроки: \n\nИсходные данные: ' + page.request)}`;
  return <main className={`${shared.page} ${styles.page} ${styles[page.layout] || ''}`} style={{ '--space-wash': wash, '--space-accent': accent }}>
    <nav className={shared.breadcrumbs} aria-label="Хлебные крошки"><a href="/">Главная</a><span aria-hidden="true">/</span><a href="/sitemap/#geography">География</a><span aria-hidden="true">/</span><span aria-current="page">{page.name}</span></nav>
    <header className={styles.hero}>
      <div className={styles.heroCopy}><p className={shared.label}>География Людно / {district ? 'Региональные проекты' : 'Игровые пространства'}</p><h1>{page.title}</h1><p className={styles.headline}>{page.headline}</p><a className={shared.textLink} href="#regional-brief">Обсудить участок <span aria-hidden="true">↘</span></a></div>
      {district ? <aside className={styles.regionCard}><p className={shared.label}>От идеи до реализации</p><span className={styles.regionName}>{page.name}</span><p>Дворы · Парки · Образовательные территории</p><ol><li>Проектирование</li><li>Подбор оборудования</li><li>Производство и поставка</li></ol><a href="#geography-links">Другие направления <Arrow /></a></aside> : <figure className={styles.heroImage}><img src={visual.image} alt={`${visual.title} — коллекция оборудования Людно`} loading="eager" /><figcaption><span>Идея для наполнения</span><a href={visual.href}>{visual.title} <Arrow /></a></figcaption></figure>}
    </header>
    <nav className={shared.sectionNav} aria-label="Разделы страницы"><a href="#local-context">Контекст участка</a><a href="#regional-solutions">Подходящие решения</a><a href="#regional-work">Как работаем</a><a href="#regional-brief">Обсудить проект <span aria-hidden="true">↘</span></a></nav>
    <section id="local-context" className={`${shared.section} ${styles.context}`}><div className={shared.sectionHeading}><p className={shared.label}>{page.name} / Подход</p><div><h2>{district ? 'Общий подход. Точные решения для каждого адреса' : 'Проект начинается с места'}</h2><p className={shared.sectionLead}>{page.lead}</p></div></div><div className={`${shared.points} ${styles.points}`}>{page.points.map(([title, text], index) => <article key={title}><span className={shared.number}>0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section id="regional-solutions" className={shared.section}><div className={shared.sectionHeading}><p className={shared.label}>Коллекции Людно</p><div><h2>{district ? 'Оборудование под разные задачи территории' : 'Возможное наполнение пространства'}</h2><p className={shared.sectionLead}>Подборка по игровым сценариям. Состав и размещение уточняем по плану, возрасту пользователей и условиям эксплуатации.</p></div></div><div className={shared.collections}>{page.collections.map(key => { const collection = spaceCollections[key]; return <a className={shared.collection} href={collection.href} key={key}><div className={shared.collectionImage}><img src={collection.image} alt={collection.title} loading="lazy" /></div><div className={shared.collectionCaption}><h3>{collection.title} <Arrow /></h3><p>{collection.text}</p><span className={shared.collectionLink}>Посмотреть решение <Arrow /></span></div></a>; })}</div></section>
    <section id="regional-work" className={`${shared.section} ${styles.work}`}><div className={shared.sectionHeading}><p className={shared.label}>Работа с командой проекта</p><h2>{district ? 'Несколько объектов — согласованный порядок работы' : 'От первого плана до комплектации'}</h2></div><ol>{stages.map(([title, text], index) => <li key={title}><span className={shared.number}>0{index + 1}</span><h3>{title}</h3><p>{text}</p></li>)}</ol><div className={styles.delivery}><p className={shared.label}>Для расчёта поставки</p><p>Нужны точный адрес, согласованный состав оборудования и условия разгрузки. Подготовку участка, монтаж или шефмонтаж обсуждаем отдельно и фиксируем в предложении.</p><a href="/postavka-igrovogo-oborudovaniya/">Подробнее о поставке <Arrow /></a></div></section>
    <section id="regional-brief" className={`${shared.brief} ${styles.brief}`}><div><p className={shared.label}>{page.name} / Ваш проект</p><h2>Расскажите об участке</h2><p className={shared.briefLead}>{page.request}</p><a className={shared.textLink} href={mail}>Отправить исходные данные <Arrow /></a></div><div className={styles.briefAside}><p className={shared.label}>Можно начать с простого</p><h3>План, фотографии и идея</h3><p>Пришлите материалы, которые уже есть. Уточним задачу, определим недостающие сведения и согласуем следующий шаг.</p><a href="https://t.me/ludno_info" target="_blank" rel="noopener noreferrer">Написать в Telegram <Arrow /></a></div></section>
    <section className={`${shared.section} ${styles.questions}`}><div className={shared.sectionHeading}><p className={shared.label}>До начала работы</p><h2>Детали реализации</h2></div><details><summary>{district ? 'Можно ли объединить несколько адресов в один проект?' : 'Можно ли начать подбор без готового проекта?'}<span aria-hidden="true">+</span></summary><p>{district ? 'Да, можно обсудить общую концепцию и комплектацию нескольких объектов. При этом для каждого адреса нужны свой план, условия доставки и график готовности. Это позволяет согласовать очереди и не смешивать комплекты документов.' : 'Для первого разговора достаточно размеров, фотографий и описания задачи. По ним можно определить направление подбора. Для окончательной расстановки, подготовки основания и монтажа состав точных исходных данных потребуется согласовать.'}</p></details><details><summary>Как определить бюджет и сроки?<span aria-hidden="true">+</span></summary><p>После уточнения оборудования, материалов, адреса и состава работ. Отдельно рассматриваем подготовку основания, покрытие, поставку и монтаж: они зависят от участка. Итоговый график согласуем с готовностью территории.</p></details></section>
    <nav id="geography-links" className={`${shared.section} ${styles.geography}`} aria-label="География проектов"><div className={shared.sectionHeading}><p className={shared.label}>Продолжить знакомство</p><h2>{district ? 'Города и регионы' : 'В этом направлении'}</h2></div><div className={styles.regionLinks}>{related.map(item => <a key={item.slug} href={`/${item.slug}/`}>{item.name}<Arrow /></a>)}{page.parent === 'moskovskaya-oblast' && <a href="/detskie-ploshchadki-moskva/">Москва<Arrow /></a>}</div><details className={styles.directory}><summary>Вся география Людно <span aria-hidden="true">+</span></summary><div>{geographyLinks.map(group => <div key={group.title}><h3>{group.title}</h3><ul>{group.links.map(link => <li key={link.href}>{link.href === `/${page.slug}/` ? <span aria-current="page">{link.title}</span> : <a href={link.href}>{link.title}</a>}</li>)}</ul></div>)}</div></details></nav>
  </main>;
}
