name: Deploy Ludno UI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          docker build -t fijispawn/ludno-ui:$COMMIT_HASH .
          docker push fijispawn/ludno-ui:$COMMIT_HASH
          docker tag fijispawn/ludno-ui:$COMMIT_HASH fijispawn/ludno-ui:latest
          docker push fijispawn/ludno-ui:latest

      - name: SSH and redeploy container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            ~/redeploy.sh
